name: 'ci-backend'

on:
  push:
    branches:
      - '**'
    paths:
      - 'apps/backend/**'
      - '.github/workflows/ci-backend.yml'

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: '${{secrets.GCP_PROJECT_ID}}'
  REGION: '${{secrets.GCP_REGION }}'
  IMAGE_NAME: backend


jobs:
  image-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{secrets.WIP}}'
          service_account: '${{secrets.GCPSA}}'

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v3
      
      - name: Docker Configuration
        run:
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run:
          docker build \
          -t ${{env.REGION}}/${{env.PROJECT_ID}}/app-repo/${{env.IMAGE_NAME}}:${{github.sha}}\
          -t ${{env.REGION}}/${{env.PROJECT_ID}}/app-repo/${{env.IMAGE_NAME}}:latest\
          . apps/backend

      - name: Push Docker Image to Artifact Registry
        if: github.ref == 'refs/head/main'
        run:
          docker push ${{env.REGION}}/${{env.PROJECT_ID}}/app-repo/${{env.IMAGE_NAME}}:${{github.sha}} 
          docker push ${{env.REGION}}/${{env.PROJECT_ID}}/app-repo/${{env.IMAGE_NAME}}:latest
          





