name: 'ci-frontend'

on:
  push:
    branches:
      - '**'
    paths:
      - 'apps/frontend/**'


permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: '${{secrets.GCP_PROJECT_ID}}'
  REGION: '${{secrets.GCP_REGION }}'
  IMAGE_NAME: frontend
  REGISTRY: us-central1-docker.pkg.dev


jobs:
  image-build-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{secrets.WIP}}'
          service_account: '${{secrets.GCPSA}}'

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v3
      
      - name: Docker Configuration
        run:
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build \
          -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:${{ github.sha }} \
          -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:latest \
          ./apps/backend

      - name: Push Docker Image to Artifact Registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/${{ env.IMAGE_NAME }}:${{ github.sha }} 
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/${{ env.IMAGE_NAME }}:latest






