name: 'Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'       # Trigger ONLY if files in /terraform/ change
      - '.github/workflows/**'
  pull_request:


    
permissions:
  contents: read
  id-token: write # Essential for WIF
jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      # 1. Authenticate using SA
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: '${{ secrets.SAGCP }}' # Replace with the name of your GitHub Actions secret
      # 2. Verify Authentication with gcloud
      - name: 'terraform init'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan \
            -var-file=env.tfvars \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve \
            -var-file=env.tfvars